### ISSUE TITLE
Renaming..

### ISSUE THREAD

**Issue by tscanlin** [tscanlin/mocha-electron#1]
Since the name is so similar to https://github.com/jprichardson/electron-mocha I'm thinking of renaming this to mochatron. Thoughts?

**Comment by tscanlin** [comment]
@madarche, would you be okay if I changed the name of this project to mochatron so it is not as easily confused with electron-mocha?

**Comment by madarche** [comment]
I agree the too similar name is disturbing and I need to double-check all the time. There might be better choices, but mochatron sounds good to me :-)

**Comment by tscanlin** [comment]
Thanks for the feedback, I've renamed the repo and will update the repo files tonight.
