### ISSUE TITLE
Point to relative path file

### ISSUE THREAD

**Issue by stevenvachon** [tscanlin/mocha-electron#5]
It'd be great if we could do this:
```shell
mocha-electron path/to/file.html
```
like [mocha-phantomjs](https://npmjs.com/mocha-phantomjs) does.

**Comment by tscanlin** [comment]
Thanks for the feature request, but this project isn't being updated anymore.

**Comment by stevenvachon** [comment]
Ok, thank you.

**Comment by tscanlin** [comment]
Actually, you could accomplish what you want with the current version if you include the full path to the file as a file:// url. Hope that helps.

```
file:///Users/<username>/Code/projects/something/index.html
```

**Comment by tscanlin** [comment]
or potentially even pass it in using PWD.

```
mochatron file://$PWD/test/index.html
```

**Comment by stevenvachon** [comment]
``` json
"scripts": {
  "test": "mochatron file://$PWD/test/index.html"
}
```

```
env: node\r: No such file or directory
```

**Comment by tscanlin** [comment]
Are you on windows or mac?

**Comment by stevenvachon** [comment]
Mac, though I would prefer to support Windows as well.

**Comment by tscanlin** [comment]
Well you need to change the path for your project.

**Comment by stevenvachon** [comment]
That _is_ the path for my project.

**Comment by tscanlin** [comment]
Well when you drag the html file to your browser you should just grab that URI and try using that instead of `file://$PWD/test/index.html`, maybe $PWD isn't working..

**Comment by stevenvachon** [comment]
Using a full path won't work with CI tools

**Comment by tscanlin** [comment]
yeah, but it could work for testing locally / troubleshooting the issue.

**Comment by stevenvachon** [comment]
I can test in Chrome manually to accomplish that. Oh well, thank you for your time!!
